apiVersion: v1
kind: Service
metadata:
  name: hadoop-service
spec:
  type: LoadBalancer
  ports:
  - port: 9870
    protocol: TCP
    targetPort: 9870
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: hadoop-namenode